package com.google.firebase.encore.koreanfood.dataModel

class FoodMap {

    // 음식 이름 :key,

    public var foodMap = mapOf(
        "0" to "Stir-fried Eggplant",
        "1" to "Soy Sauce Marinated Crab",
        "2" to "Grilled Spareribs",
        "3" to "Braised Short Ribs",
        "4" to "Short Rib Soup",
        "5" to "Grilled Cutlassfish",
        "6" to "Braised Cutlassfish",
        "7" to "Potato Pancake",
        "8" to "Braised Potatoes",
        "9" to "Stir-fried Potatoes",
        "10" to "Pork Back-bone Stew",
        "11" to "Leaf Mustard Kimchi",
        "12" to "Stir-fried Dried Shrimps",
        "13" to "Sweet Rice Balls",
        "14" to "Egg soup",
        "15" to "Rolled Omelet",
        "16" to "Steamed Eggs",
        "17" to "Fried egg",
        "18" to "Grilled Mackerel",
        "19" to "Braised Mackerel",
        "20" to "Bracken Salad",
        "21" to "Stir-fired Dried Squid and Red Pepper paste",
        "22" to "Fried pepper",
        "23" to "Beef Bone Soup",
        "24" to "Grilled Beef TripeGrilled Pork Tripe",
        "25" to "Beef Tripe Hot Pot",
        "26" to "Half-dried Saury",
        "27" to "Gimbap",
        "28" to "Kimchi Fried Rice",
        "29" to "Kimchi Pancake",
        "30" to "Kimchi Stew",
        "31" to "Braised Kimchi",
        "32" to "Diced Radish Kimchi",
        "33" to "Pickled perilla leaf",
        "34" to "Steamed Cockles",
        "35" to "Boiled Pacific saury",
        "36" to "Chili pepper salad",
        "37" to "Honey-filled Rice Cake",
        "38" to "Water Kimchi",
        "39" to "Scorched Rice",
        "40" to "Spicy Stir-fried Chicken",
        "41" to "Spicy chicken soup",
        "42" to "Spicy Braised Chicken",
        "43" to "Grilled Deodeok",
        "44" to "Balloon flower root salad",
        "45" to "Acorn Jelly Salad",
        "46" to "Meat Fritters",
        "47" to "Pollack Stew",
        "48" to "Soybean Paste Stew",
        "49" to "Bean Curd with Stir-fried Kimchi",
        "50" to "Braised Bean Curd",
        "51" to "Braised Peanuts",
        "52" to "Grilled Short Rib Patties",
        "53" to "Sliced Rice Cake Soup",
        "54" to "Rice Cake Skewers",
        "55" to "Stir-fried Rice Cake",
        "56" to "Ramen",
        "57" to "Stir-fried Instant Noodle",
        "58" to "Buckwheat Noodles",
        "59" to "Dumplings",
        "60" to "Spicy Fish Stew",
        "61" to "Sea squirt",
        "62" to "Braised Quail Eggs in Soy Sauce",
        "63" to "Stir-fried Dried Anchovies",
        "64" to "Radish Soup",
        "65" to "Julienne Radish Fresh Salad",
        "66" to "Cold Buckwheat Noodles",
        "67" to "Cold Raw Fish Soup",
        "68" to "Seaweed Soup",
        "69" to "Stir-fried Seaweed Stems",
        "70" to "Kimchi",
        "71" to "White Kimchi",
        "72" to "Napa Wraps with Pork",
        "73" to "Chive Kimchi",
        "74" to "Dried Pollack Soup",
        "75" to "Bulgogi",
        "76" to "Spicy Buckwheat Noodles",
        "77" to "Bibimbap",
        "78" to "Live Octopus",
        "79" to "Grilled Pork Belly",
        "80" to "Ginseng Chicken Soup",
        "81" to "Shrimp Fried Rice",
        "82" to "Deep-fried Shrimp",
        "83" to "Pan-fried Battered Fish-fillets",
        "84" to "Stir-fried sausage",
        "85" to "Half-moon Rice Cake",
        "86" to "Boiled Beef SlicesBoiled Pork Slices",
        "87" to "Cinnamon Punch",
        "88" to "Hand-pulled Dough Soup",
        "89" to "Mung Bean Sprout Salad",
        "90" to "Blood Sausage",
        "91" to "Soft Bean Curd Stew",
        "92" to "Spinach Salad",
        "93" to "Soybean Paste Soup with Dried Radish Leaves",
        "94" to "Sweet Rice Punch",
        "95" to "Fish Roe Rice",
        "96" to "Stir-fried Zucchini",
        "97" to "Honey Cookie",
        "98" to "Sweet Rice with Nuts and Jujubes",
        "99" to "Spicy Marinated Crab",
        "100" to "Seasoned Fried Chicken",
        "101" to "Stir-fried Fishcake",
        "102" to "Braised Lotus Roots",
        "103" to "Young Summer Radish KimchiNoodles",
        "104" to "Young Summer Radish Kimchi",
        "105" to "Cucumber Kimchi",
        "106" to "Stir-fried Dried Squid Strips",
        "107" to "Deep-fried Squid",
        "108" to "Braised Burdock Roots",
        "109" to "Fried Tofu Rice Balls",
        "110" to "Spicy Beef Soup",
        "111" to "Beef Tartare",
        "112" to "Banquet Noodles",
        "113" to "Steamed Multi-grain Rice",
        "114" to "Stir-fried Glass Noodles andVegetables",
        "115" to "Grilled Eel",
        "116" to "Braised Beef in Soy Sauce",
        "117" to "Abalone Porridge",
        "118" to "Salted Seafood",
        "119" to "Stir-fried Pork",
        "120" to "Grilled Clams",
        "121" to "Grilled Yellow Croaker",
        "122" to "Braised Pigs' Feet",
        "123" to "Stir-fried Webfoot Octopus",
        "124" to "Riceballs",
        "125" to "Noodles with Black Soybean Sauce",
        "126" to "Spicy Seafood Noodle Soup",
        "127" to "Spicy Chewy Noodles",
        "128" to "Braised Chicken",
        "129" to "Whole Radish Kimchi",
        "130" to "Loach Soup",
        "131" to "Noodle Soup",
        "132" to "Braised Half-dried Pollack",
        "133" to "Noodles in Cold Soybean Soup",
        "134" to "Bean Sprout Soup",
        "135" to "Bean Sprout Salad",
        "136" to "Cooked beans",
        "137" to "Green Onion Kimchi",
        "138" to "Green Onion Pancake",
        "139" to "Sliced Pork",
        "140" to "Pizza",
        "141" to "Hangwa",
        "142" to "Spicy Braised Seafood",
        "143" to "Pan-fried Battered Zucchini",
        "144" to "Pumpkin Porridge",
        "145" to "Hongeohoemuchim",
        "146" to "Grilled Dried Pollack",
        "147" to "Spicy Raw Fish Salad",
        "148" to "Fried chicken",
        "149" to "Smoked Duck"
        )


}